### ISSUE TITLE
[feat] alarm_list / 지난 알림 다가오는 알림 더보기 액티비티 생성 및 뷰작업

### ISSUE THREAD

**Issue by 2chang5** [TeamPhotoSurfer/PhotoSurfer-Android#50]
## 화면 이름
alarm/지난알림,alarm/다가오는 알림

## 기능 설명
지난알림 다가오는 알림 더보기 부분 ui작압

## 필요 태스크
- [x] 지난 알림
- [x] 다가오는 알림

**Comment by KxxHyoRim** [comment]
코드리뷰 안해줌 ㅡ.,ㅡ
